# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68ce64c24d40c66db227d244288ff5236c7f43eea60b31c277f274167e2e4e128454ec1568db077414b9c86755b2a47baa1383e2b792e29468c8f6c7411d65f6

test:
  secret_key_base: 0bfdc98f2c2c55e09ec41bd57d26a4d5715177ec635dd3f1d3749999d6036ad42d6d9427f7b77b88f6392d949ddc46c54036dd58935dfa514ccd40661961523c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
